# Shadow.pdf mapping:
#   Plot utility for Problem 1/2/3/4 outputs generated by:
#   - normal.jl and hidden_non_normal.jl (Problem 1)
#   - problem2_k_shadow.jl
#   - problem3_c_shadow.jl
#   - problem4_C_shadow.jl
#
# Run from repository root:
#   julia --project=examples examples/plot_problem_shadows.jl

using CairoMakie
using HDF5
using Printf

const MAX_BINS_PER_DIM = 1000
const DEFAULT_HIDDEN_ANIMATION_FPS = 18
const CONTRAST_CMAP = cgrad([:white, :slateblue4, :deepskyblue3, :gold2, :orangered3, :maroon4])

const TITLE_BY_STEM = Dict(
    "normal_complex" => "Problem 1 baseline: normal matrix (complex vectors)",
    "normal_real" => "Problem 1 baseline: normal matrix (real vectors)",
    "problem2_k_shadow_n=6_k=3" => "Problem 2: k-numerical shadow (k=3, n=6)",
    "problem3_c_shadow_n=6" => "Problem 3: c-numerical shadow (n=6)",
    "problem4_C_shadow_n=6" => "Problem 4: C-numerical shadow (n=6)",
)

function title_for_stem(stem::AbstractString)
    if haskey(TITLE_BY_STEM, stem)
        return TITLE_BY_STEM[stem]
    end
    if startswith(stem, "hidden_non_normal_complex_")
        d = replace(stem, "hidden_non_normal_complex_" => "")
        return "Problem 1: hidden non-normal (complex vectors), d = $d"
    end
    if startswith(stem, "hidden_non_normal_real_")
        d = replace(stem, "hidden_non_normal_real_" => "")
        return "Problem 1: hidden non-normal (real vectors), d = $d"
    end
    return stem
end

env_flag(name::AbstractString, default::Bool) =
    lowercase(get(ENV, name, default ? "true" : "false")) in ("1", "true", "yes")

function edge_centers(edges::AbstractVector)
    length(edges) >= 2 || throw(ArgumentError("Need at least two edges."))
    @views (edges[1:end-1] .+ edges[2:end]) ./ 2
end

function _rebinned_edges(edges::AbstractVector, factor::Int)
    n = length(edges) - 1
    n > 0 || throw(ArgumentError("Need at least one bin edge interval."))
    factor > 0 || throw(ArgumentError("`factor` must be positive, got $factor"))

    idx = Int[1]
    i = factor + 1
    while i < n + 1
        push!(idx, i)
        i += factor
    end
    push!(idx, n + 1)
    return edges[idx]
end

function rebin_histogram(
    hist::AbstractMatrix,
    x_edges::AbstractVector,
    y_edges::AbstractVector;
    max_bins_per_dim::Int = MAX_BINS_PER_DIM,
)
    max_bins_per_dim > 0 || throw(ArgumentError("`max_bins_per_dim` must be positive"))

    nx, ny = size(hist)
    fx = max(1, cld(nx, max_bins_per_dim))
    fy = max(1, cld(ny, max_bins_per_dim))

    nx_new = cld(nx, fx)
    ny_new = cld(ny, fy)
    out = zeros(Float64, nx_new, ny_new)

    for ix_new in 1:nx_new
        ix_start = (ix_new - 1) * fx + 1
        ix_end = min(ix_new * fx, nx)
        for iy_new in 1:ny_new
            iy_start = (iy_new - 1) * fy + 1
            iy_end = min(iy_new * fy, ny)
            @views out[ix_new, iy_new] = sum(hist[ix_start:ix_end, iy_start:iy_end])
        end
    end

    x_edges_new = _rebinned_edges(x_edges, fx)
    y_edges_new = _rebinned_edges(y_edges, fy)
    return out, x_edges_new, y_edges_new
end

function normalize_histogram(hist::AbstractMatrix)
    h = Float64.(hist)
    total = sum(h)
    if total > 0
        h ./= total
    end
    return h
end

function maybe_plot_polygon!(ax, points, color, label)
    points isa AbstractMatrix || return false
    size(points, 2) == 2 || return false
    size(points, 1) >= 3 || return false
    closed = vcat(points, points[1:1, :])
    lines!(ax, closed[:, 1], closed[:, 2]; color = color, linewidth = 2, label = label)
    return true
end

function closed_polygon(points)
    points isa AbstractMatrix || return nothing
    size(points, 2) == 2 || return nothing
    size(points, 1) >= 3 || return nothing
    return vcat(points, points[1:1, :])
end

function read_shadow_file(fname::AbstractString)
    data = Dict{String,Any}()
    HDF5.h5open(fname, "r") do io
        for key in keys(io)
            data[String(key)] = read(io[key])
        end
    end
    return data
end

function prepare_shadow_payload(data::Dict{String,Any})
    x_edges = vec(Array(data["x_edges"]))
    y_edges = vec(Array(data["y_edges"]))
    hist = Array(data["hist"])
    hist, x_edges, y_edges = rebin_histogram(hist, x_edges, y_edges)
    hist = normalize_histogram(hist)
    display_hist = sqrt.(hist)

    nr_points = haskey(data, "nr") ? closed_polygon(Array(data["nr"])) : nothing
    other_points = haskey(data, "other_range") ? closed_polygon(Array(data["other_range"])) : nothing
    evs = haskey(data, "evs") ? vec(Array(data["evs"])) : ComplexF64[]

    return (
        x_edges = x_edges,
        y_edges = y_edges,
        x_centers = edge_centers(x_edges),
        y_centers = edge_centers(y_edges),
        display_hist = display_hist,
        nr_points = nr_points,
        other_points = other_points,
        evs = evs,
    )
end

function plot_shadow_file(h5_path::AbstractString, out_dir::AbstractString)
    data = read_shadow_file(h5_path)
    stem = splitext(basename(h5_path))[1]
    payload = prepare_shadow_payload(data)

    fig = Figure(size = (920, 760))
    ax = Axis(
        fig[1, 1];
        xlabel = "Re(z)",
        ylabel = "Im(z)",
        title = title_for_stem(stem),
        aspect = DataAspect(),
    )

    max_hist = max(maximum(payload.display_hist), eps(Float64))
    heatmap!(
        ax,
        payload.x_centers,
        payload.y_centers,
        payload.display_hist;
        colormap = CONTRAST_CMAP,
        colorrange = (0.0, max_hist),
    )

    has_legend_entries = false
    if payload.nr_points !== nothing
        has_legend_entries |= maybe_plot_polygon!(ax, payload.nr_points, :cyan, "numerical range")
    end
    if payload.other_points !== nothing
        has_legend_entries |= maybe_plot_polygon!(ax, payload.other_points, :lime, "other range")
    end
    if !isempty(payload.evs)
        scatter!(
            ax,
            real.(payload.evs),
            imag.(payload.evs);
            color = :gold,
            marker = :diamond,
            markersize = 13,
            strokecolor = :black,
            strokewidth = 1.2,
            label = "eigenvalues",
        )
        has_legend_entries = true
    end

    xlims!(ax, first(payload.x_edges), last(payload.x_edges))
    ylims!(ax, first(payload.y_edges), last(payload.y_edges))
    if has_legend_entries
        axislegend(ax; position = :rt)
    end

    mkpath(out_dir)
    out_path = joinpath(out_dir, "$(stem).png")
    save(out_path, fig)
    println("Saved: $out_path")
    return out_path
end

function parse_hidden_parameter(stem::AbstractString, prefix::AbstractString)
    startswith(stem, prefix) || return nothing
    d_str = replace(stem, prefix => "")
    return tryparse(Float64, d_str)
end

function hidden_non_normal_frames(files::AbstractVector{<:AbstractString}, family::Symbol)
    family ∈ (:complex, :real) ||
        throw(ArgumentError("`family` must be :complex or :real, got $family"))
    prefix = family === :complex ? "hidden_non_normal_complex_" : "hidden_non_normal_real_"

    frames = Tuple{Float64,String}[]
    for file in files
        stem = splitext(basename(file))[1]
        d = parse_hidden_parameter(stem, prefix)
        d === nothing && continue
        push!(frames, (d, String(file)))
    end
    sort!(frames; by = first)
    return frames
end

function animate_hidden_non_normal_family(
    frames::AbstractVector{<:Tuple{<:Real,<:AbstractString}},
    out_path::AbstractString;
    family_label::AbstractString,
    fps::Int = DEFAULT_HIDDEN_ANIMATION_FPS,
)
    length(frames) >= 2 ||
        throw(ArgumentError("Need at least two frames to build animation, got $(length(frames))"))
    fps > 0 || throw(ArgumentError("`fps` must be positive, got $fps"))

    x_min = Inf
    x_max = -Inf
    y_min = Inf
    y_max = -Inf
    max_display_hist = 0.0
    for (_, file) in frames
        payload = prepare_shadow_payload(read_shadow_file(file))
        x_min = min(x_min, first(payload.x_edges))
        x_max = max(x_max, last(payload.x_edges))
        y_min = min(y_min, first(payload.y_edges))
        y_max = max(y_max, last(payload.y_edges))
        max_display_hist = max(max_display_hist, maximum(payload.display_hist))
    end
    max_display_hist = max(max_display_hist, eps(Float64))

    x_obs = Observable([0.0, 1.0])
    y_obs = Observable([0.0, 1.0])
    hist_obs = Observable(zeros(Float64, 2, 2))
    nr_x_obs = Observable(Float64[])
    nr_y_obs = Observable(Float64[])
    other_x_obs = Observable(Float64[])
    other_y_obs = Observable(Float64[])
    ev_x_obs = Observable(Float64[])
    ev_y_obs = Observable(Float64[])

    fig = Figure(size = (920, 760))
    ax = Axis(
        fig[1, 1];
        xlabel = "Re(z)",
        ylabel = "Im(z)",
        title = "Problem 1: hidden non-normal ($family_label)",
        aspect = DataAspect(),
    )
    heatmap!(
        ax,
        x_obs,
        y_obs,
        hist_obs;
        colormap = CONTRAST_CMAP,
        colorrange = (0.0, max_display_hist),
    )
    lines!(ax, nr_x_obs, nr_y_obs; color = :cyan, linewidth = 2, label = "numerical range")
    lines!(ax, other_x_obs, other_y_obs; color = :lime, linewidth = 2, label = "other range")
    scatter!(
        ax,
        ev_x_obs,
        ev_y_obs;
        color = :gold,
        marker = :diamond,
        markersize = 13,
        strokecolor = :black,
        strokewidth = 1.2,
        label = "eigenvalues",
    )
    axislegend(ax; position = :rt)
    xlims!(ax, x_min, x_max)
    ylims!(ax, y_min, y_max)

    function set_frame!(frame_idx::Int)
        d, file = frames[frame_idx]
        payload = prepare_shadow_payload(read_shadow_file(file))
        x_obs[] = payload.x_centers
        y_obs[] = payload.y_centers
        hist_obs[] = payload.display_hist

        if payload.nr_points === nothing
            nr_x_obs[] = Float64[]
            nr_y_obs[] = Float64[]
        else
            nr_x_obs[] = Float64.(payload.nr_points[:, 1])
            nr_y_obs[] = Float64.(payload.nr_points[:, 2])
        end

        if payload.other_points === nothing
            other_x_obs[] = Float64[]
            other_y_obs[] = Float64[]
        else
            other_x_obs[] = Float64.(payload.other_points[:, 1])
            other_y_obs[] = Float64.(payload.other_points[:, 2])
        end

        ev_x_obs[] = Float64.(real.(payload.evs))
        ev_y_obs[] = Float64.(imag.(payload.evs))
        ax.title = "Problem 1: hidden non-normal ($family_label), d = $(@sprintf("%.2f", d))"
        return nothing
    end

    mkpath(dirname(out_path))
    set_frame!(1)
    record(fig, out_path, eachindex(frames); framerate = fps) do frame_idx
        set_frame!(frame_idx)
    end
    println("Saved animation: $out_path")
    return out_path
end

function maybe_generate_hidden_non_normal_animations(
    files::AbstractVector{<:AbstractString},
    out_dir::AbstractString,
)
    env_flag("NUMERICALSHADOW_MAKE_HIDDEN_ANIMATIONS", true) || return nothing

    fps = parse(Int, get(ENV, "NUMERICALSHADOW_HIDDEN_ANIMATION_FPS", string(DEFAULT_HIDDEN_ANIMATION_FPS)))
    ext = lowercase(get(ENV, "NUMERICALSHADOW_HIDDEN_ANIMATION_EXT", "mp4"))
    ext in ("mp4", "gif", "webm", "mkv") ||
        throw(ArgumentError("Unsupported animation extension '$ext'"))

    complex_frames = hidden_non_normal_frames(files, :complex)
    real_frames = hidden_non_normal_frames(files, :real)
    if length(complex_frames) >= 2
        animate_hidden_non_normal_family(
            complex_frames,
            joinpath(out_dir, "hidden_non_normal_complex.$ext");
            family_label = "complex vectors",
            fps = fps,
        )
    end
    if length(real_frames) >= 2
        animate_hidden_non_normal_family(
            real_frames,
            joinpath(out_dir, "hidden_non_normal_real.$ext");
            family_label = "real vectors",
            fps = fps,
        )
    end
    return nothing
end

function main()
    results_dir = joinpath(@__DIR__, "results")
    isdir(results_dir) || throw(ArgumentError("Results directory not found: $results_dir"))

    is_problem_file(f) = begin
        stem = splitext(basename(f))[1]
        endswith(f, ".h5") && (
            startswith(stem, "problem") ||
            startswith(stem, "normal_") ||
            startswith(stem, "hidden_non_normal_")
        )
    end
    files = sort(filter(is_problem_file, readdir(results_dir; join = true)))
    isempty(files) && throw(ArgumentError("No Problem 1/2/3/4 .h5 files found in $results_dir"))

    out_dir = joinpath(results_dir, "plots")
    println("Plotting $(length(files)) file(s) from $results_dir")
    for file in files
        plot_shadow_file(file, out_dir)
    end
    maybe_generate_hidden_non_normal_animations(files, out_dir)
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
